# Usar a imagem oficial do PHP com Apache
FROM php:8.3-apache

# Habilitar módulo mod_rewrite do Apache
RUN a2enmod rewrite

# Copiar os arquivos do diretório atual (onde está o Dockerfile) para o Apache
COPY ./ /var/www/html/

# Expor a porta 80
EXPOSE 80
