version: '3.9'

services:
  php:
    build: .
    container_name: php-container
    ports:
      - "8080:80"  # Mapeia a porta 8080 do host para a porta 80 do contêiner
    volumes:
      - .:/var/www/html  # Mapeia todos os arquivos do seu projeto para dentro do contêiner

